LiashenkoAndrey/talk-and-travel

src/main/java/online/talkandtravel/config/SecurityConfiguration.java
src/main/java/online/talkandtravel/config/WebSocketConfig.java

allow url https://oleksandrprokopenkodev.github.io/websocket-util/

add websocket tool

---

src/main/java/online/talkandtravel/controller/http/ChatController.java
src/main/java/online/talkandtravel/exception/user/UserChatNotFoundException.java
src/main/java/online/talkandtravel/model/dto/chat/SetLastReadMessageDtoRequest.java
src/main/java/online/talkandtravel/model/dto/chat/SetLastReadMessageRequest.java
src/main/java/online/talkandtravel/repository/MessageRepository.java
src/main/java/online/talkandtravel/service/ChatService.java
src/main/java/online/talkandtravel/service/impl/ChatServiceImpl.java
src/main/java/online/talkandtravel/util/mapper/ChatMapper.java
src/main/java/online/talkandtravel/util/mapper/UserChatMapper.java

Need to create an endpoint that will set last_read_message_id into userChats table.
/{chatId}/messages/set-last-read-message
Create two additional endpoints 
/{chatId}/read-messages"that return Page<MessageDtoBasic> starting with lastReadMessage and contains read messages + last read message 
/{chatId}/unread-messages"that return Page<MessageDtoBasic> starting with lastReadMessage and contains UNread messages

Last Read Message feature

---

src/main/java/online/talkandtravel/controller/websocket/MessageController.java
src/main/java/online/talkandtravel/service/MessageService.java
src/main/java/online/talkandtravel/service/impl/MessageServiceImpl.java
src/test/java/online/talkandtravel/service/impl/MessageServiceImplTest.java

{
"id": 14,
"content": "new message",
"creationDate": "2024-08-14T18:09:29.19352",
"user": {
"id": 1,
"userName": "admin"
},
"chatId": 485,
"repliedMessageId": null
}

MessageDto contains username

---

src/test/java/online/talkandtravel/service/impl/ChatServiceImplTest.java

added tests for createPrivateChat method

KAN 59 (Create Private chat ) Add tests

---

src/test/java/online/talkandtravel/service/impl/ChatServiceImplTest.java

KAN 26 ok test

---

docs/websockets/error-handling.md
src/main/java/online/talkandtravel/config/JwtAuthenticationFilter.java
src/main/java/online/talkandtravel/config/WebSocketConfig.java
src/main/java/online/talkandtravel/exception/auth/RegistrationException.java
src/main/java/online/talkandtravel/exception/auth/UserAuthenticationException.java
src/main/java/online/talkandtravel/exception/chat/ChatNotFoundException.java
src/main/java/online/talkandtravel/exception/chat/MainCountryChatNotFoundException.java
src/main/java/online/talkandtravel/exception/chat/PrivateChatAlreadyExistsException.java
src/main/java/online/talkandtravel/exception/chat/UserNotJoinedTheChatException.java
src/main/java/online/talkandtravel/exception/country/CountryNotFoundException.java
src/main/java/online/talkandtravel/exception/data/FailedToReadJsonException.java
src/main/java/online/talkandtravel/exception/file/FileSizeExceededException.java
src/main/java/online/talkandtravel/exception/file/ImageProcessingException.java
src/main/java/online/talkandtravel/exception/file/ImageWriteException.java
src/main/java/online/talkandtravel/exception/file/UnsupportedFormatException.java
src/main/java/online/talkandtravel/exception/message/MessageNotFoundException.java
src/main/java/online/talkandtravel/exception/model/ExceptionResponse.java
src/main/java/online/talkandtravel/exception/model/HttpException.java
src/main/java/online/talkandtravel/exception/model/HttpExceptionHandler.java
src/main/java/online/talkandtravel/exception/model/WebSocketException.java
src/main/java/online/talkandtravel/exception/model/WebSocketExceptionHandler.java
src/main/java/online/talkandtravel/exception/user/UserAlreadyJoinTheChatException.java
src/main/java/online/talkandtravel/exception/user/UserChatNotFoundException.java
src/main/java/online/talkandtravel/exception/user/UserCountryNotFoundException.java
src/main/java/online/talkandtravel/exception/user/UserNotFoundException.java
src/main/java/online/talkandtravel/security/CustomUserDetails.java
src/main/java/online/talkandtravel/service/impl/EventServiceImpl.java
src/main/java/online/talkandtravel/service/impl/MessageServiceImpl.java
src/test/java/online/talkandtravel/service/impl/EventServiceImplTest.java
src/test/java/online/talkandtravel/service/impl/MessageServiceImplTest.java

ticket https://lizavol9.atlassian.net/browse/KAN-73
doc https://lizavol9.atlassian.net/wiki/spaces/SD/pages/13893634/Error+Handling+in+WebSocket+requests
demo:https://youtu.be/9ZwxjuiLS9Y

KAN-73 webSocket error handling

---

src/main/java/online/talkandtravel/controller/websocket/EventController.java
src/main/java/online/talkandtravel/exception/model/WebSocketException.java
src/main/java/online/talkandtravel/model/dto/event/EventDtoBasic.java
src/main/java/online/talkandtravel/model/dto/event/EventResponse.java
src/main/java/online/talkandtravel/service/EventService.java
src/main/java/online/talkandtravel/service/impl/EventServiceImpl.java
src/test/java/online/talkandtravel/service/impl/EventServiceImplTest.java

ticket https://lizavol9.atlassian.net/browse/KAN-64

KAN 64  do not save Typing Events into DB

---

src/main/java/online/talkandtravel/controller/http/AvatarController.java
src/main/java/online/talkandtravel/exception/avatar/UserAvatarNotFoundException.java
src/main/java/online/talkandtravel/exception/model/GlobalExceptionHandler.java
src/main/java/online/talkandtravel/exception/model/HttpExceptionHandler.java
src/main/java/online/talkandtravel/model/dto/LoginDto.java
src/main/java/online/talkandtravel/service/AvatarService.java
src/main/java/online/talkandtravel/service/impl/AvatarServiceImpl.java
src/test/java/online/talkandtravel/service/impl/AvatarServiceImplTest.java

When trying to upload avatar, getting response 403 NotAuthorized
changes:
1. added new exception class online.talkandtravel.exception.avatar.UserAvatarNotFoundException
2. renamed and fixed method getAvatar
3. added test

fix Upload avatar endpoint

---

src/main/java/online/talkandtravel/controller/http/ChatController.java
src/main/java/online/talkandtravel/repository/ChatRepository.java
src/main/java/online/talkandtravel/service/ChatService.java
src/main/java/online/talkandtravel/service/impl/ChatServiceImpl.java

https://lizavol9.atlassian.net/browse/KAN-97

Find all chats returns Group chats only

---

src/main/java/online/talkandtravel/controller/http/ChatController.java

https://lizavol9.atlassian.net/browse/KAN-100

setLastReadMessage - PATCH with 204 status response.

---

src/main/java/online/talkandtravel/model/dto/country/CountryDto.java

https://lizavol9.atlassian.net/browse/KAN-101
{
"name": "Aruba",
"flagCode": "aw",
"chats": [
{
"id": 732,
"name": "Food2",
"description": "2all who like food, welcome!",
"chatType": "GROUP",
"creationDate": "2024-08-17T15:34:12.49505",
"usersCount": 1,
"messagesCount": 0
},
{
"id": 736,
"name": "Food4",
"description": "4all who like food, welcome!",
"chatType": "GROUP",
"creationDate": "2024-08-17T18:49:22.545968",
"usersCount": 1,
"messagesCount": 0
},
{
"id": 485,
"name": "Aruba",
"description": "Aruba main chat",
"chatType": "GROUP",
"creationDate": "2024-08-07T13:29:35.901908",
"usersCount": 6,
"messagesCount": 17
}
]
}

KAN-101 remove list of Messages, place MessageCount in CountryDto

---

src/main/java/online/talkandtravel/controller/http/ChatController.java
src/main/java/online/talkandtravel/service/ChatService.java
src/main/java/online/talkandtravel/service/impl/ChatServiceImpl.java
src/test/java/online/talkandtravel/service/impl/unittest/ChatServiceImplTest.java

https://lizavol9.atlassian.net/browse/KAN-99

KAN-99 getRead and getUnRead messages  fetch lastReadMessageId from db

---

src/main/java/online/talkandtravel/model/entity/User.java
src/test/java/online/talkandtravel/config/IntegrationTest.java
src/test/java/online/talkandtravel/config/TestConfig.java
src/test/java/online/talkandtravel/config/TestDataConstant.java
src/test/java/online/talkandtravel/controller/http/ChatControllerIntegrationTest.java
src/test/java/online/talkandtravel/testdata/UserTestData.java
src/test/java/online/talkandtravel/util/TestAuthenticationService.java
src/test/resources/testdata/users-test-data.sql

this is a part of ticket:
https://lizavol9.atlassian.net/browse/KAN-80

Integration test fro `create private chat` endpoint

---

src/main/java/online/talkandtravel/controller/http/ChatController.java
src/test/java/online/talkandtravel/controller/http/integrationtest/ChatControllerIntegrationTest.java
src/test/java/online/talkandtravel/service/impl/integrationtest/ChatServiceIntegrationTest.java
src/test/java/online/talkandtravel/testdata/ChatTestData.java
src/test/java/online/talkandtravel/util/TestAuthenticationService.java
src/test/java/online/talkandtravel/util/TestChatService.java

ticket - https://lizavol9.atlassian.net/browse/KAN-80?atlOrigin=eyJpIjoiNTk2YWI1OGE4NzM2NGMzMjg5NGY0NGFkMjAyYWU5MDYiLCJwIjoiaiJ9

Integration tests for endpoints

---

src/main/java/online/talkandtravel/config/websocket/WebSocketConfig.java
src/main/java/online/talkandtravel/controller/websocket/EventController.java
src/main/java/online/talkandtravel/controller/websocket/MessageController.java
src/main/java/online/talkandtravel/exception/model/HttpExceptionHandler.java
src/main/java/online/talkandtravel/exception/model/WebSocketExceptionHandler.java
src/main/java/online/talkandtravel/exception/util/ExceptionHandlerUtils.java
src/main/java/online/talkandtravel/service/impl/EventServiceImpl.java
src/main/java/online/talkandtravel/util/constants/ApiPathConstants.java
src/test/java/online/talkandtravel/controller/websocket/integrationtest/EventControllerIntegrationTest.java
src/test/java/online/talkandtravel/controller/websocket/integrationtest/MessageControllerIntegrationTest.java
src/test/java/online/talkandtravel/service/impl/integrationtest/OnlineServiceWebsocketIntegrationTest.java

ticket - https://lizavol9.atlassian.net/browse/KAN-106?atlOrigin=eyJpIjoiZDFiODE0MDZlMzg0NGEwMmIxZDQ5ODE2NDFlYTM2MmMiLCJwIjoiaiJ9

Rename websocket endpoint `countries

---

requests/chat.http
requests/http-client.private.env.json
src/main/java/online/talkandtravel/controller/http/ChatController.java
src/main/java/online/talkandtravel/exception/model/HttpException.java
src/main/java/online/talkandtravel/exception/model/HttpExceptionHandler.java
src/main/java/online/talkandtravel/model/dto/chat/BasicChatInfoDto.java
src/main/java/online/talkandtravel/model/dto/user/UpdateUserRequest.java
src/main/java/online/talkandtravel/service/ChatService.java
src/main/java/online/talkandtravel/service/impl/ChatServiceImpl.java
src/main/java/online/talkandtravel/util/mapper/ChatMapper.java
src/test/java/online/talkandtravel/service/impl/unittest/ChatServiceImplTest.java

ticket - https://lizavol9.atlassian.net/browse/KAN-171?atlOrigin=eyJpIjoiMzI3YjQ1YzI4ZjU4NDEyMGExNWQ0ODhiMmE0YzZjMzkiLCJwIjoiaiJ9
doc - https://lizavol9.atlassian.net/wiki/x/AQCxAg

Add endpoint to select all main countries chats

---

requests/chat.http
src/main/java/online/talkandtravel/controller/http/ChatController.java
src/main/java/online/talkandtravel/repository/MessageRepository.java
src/main/java/online/talkandtravel/service/ChatService.java
src/main/java/online/talkandtravel/service/impl/ChatServiceImpl.java
src/test/java/online/talkandtravel/service/impl/integrationtest/ChatServiceIntegrationTest.java
src/test/java/online/talkandtravel/service/impl/unittest/ChatServiceImplTest.java

ticket - https://lizavol9.atlassian.net/browse/KAN-169?atlOrigin=eyJpIjoiN2I3MWYwZDY3MmU5NDVjYWFlNTY5YTNkZTA0NDg1Y2YiLCJwIjoiaiJ9
doc - https://lizavol9.atlassian.net/wiki/spaces/SD/pages/44892242/Correct+loading+of+read+chat+messages

Fix read messages loading 

---

requests/chat.http
requests/onlineStatus.http
requests/test.http
src/main/java/online/talkandtravel/config/SecurityConfiguration.java
src/main/java/online/talkandtravel/controller/http/AuthenticationController.java
src/main/java/online/talkandtravel/controller/http/PrivacyPolicyAndUseTerms.java
src/main/java/online/talkandtravel/facade/AuthenticationFacade.java
src/main/java/online/talkandtravel/facade/impl/AuthenticationFacadeImpl.java
src/main/java/online/talkandtravel/model/dto/auth/SocialLoginRequest.java
src/main/java/online/talkandtravel/model/dto/auth/SocialRegisterRequest.java
src/main/java/online/talkandtravel/model/entity/User.java
src/main/java/online/talkandtravel/service/AuthenticationService.java
src/main/java/online/talkandtravel/service/UserService.java
src/main/java/online/talkandtravel/service/impl/AuthenticationServiceImpl.java
src/main/java/online/talkandtravel/service/impl/UserServiceImpl.java
src/main/java/online/talkandtravel/util/mapper/UserMapper.java
src/main/resources/db/migration/V11__remove_not_null_constraint_user_password.sql

ticket - https://lizavol9.atlassian.net/browse/KAN-175?atlOrigin=eyJpIjoiYzU0MzgxYzhkMjNkNGVkNmI1Njg5ODVmNTAwYzA4ZmUiLCJwIjoiaiJ9
doc - https://lizavol9.atlassian.net/wiki/spaces/SD/pages/46727183/Facebook+and+Google+social+authentication+feature

Create register and login for social

---

requests/avatars.http
src/main/java/online/talkandtravel/service/impl/AvatarServiceImpl.java
src/main/java/online/talkandtravel/util/constants/S3Constants.java
src/main/java/online/talkandtravel/util/mapper/UserMapper.java
src/main/resources/application-prod.properties
src/main/resources/application.properties

ticket - https://lizavol9.atlassian.net/browse/KAN-179?atlOrigin=eyJpIjoiMmFiODQ2OWU2NDcxNDdiZTljZmM3NmM5MTNiZjFhOTEiLCJwIjoiaiJ9

2. Store users avatars in S3

---

src/main/java/online/talkandtravel/controller/websocket/EventController.java
src/main/java/online/talkandtravel/exception/model/WebSocketExceptionHandler.java
src/main/java/online/talkandtravel/model/entity/Message.java
src/main/java/online/talkandtravel/service/EventService.java
src/main/java/online/talkandtravel/service/impl/EventServiceImpl.java
src/test/java/online/talkandtravel/service/impl/unittest/EventServiceImplTest.java

ticket - https://lizavol9.atlassian.net/browse/KAN-194?atlOrigin=eyJpIjoiMTQyNTY2M2EzM2Y5NDRjOTllMDAxY2MwNzUxNDUzYmYiLCJwIjoiaiJ9

KAN-194 Delete private chat when leave

---

src/main/java/online/talkandtravel/controller/http/UserController.java
src/main/java/online/talkandtravel/facade/UserFacade.java
src/main/java/online/talkandtravel/facade/impl/UserFacadeImpl.java
src/main/java/online/talkandtravel/repository/AvatarRepository.java
src/main/java/online/talkandtravel/service/AvatarService.java
src/main/java/online/talkandtravel/service/UserService.java
src/main/java/online/talkandtravel/service/impl/AvatarServiceImpl.java
src/main/java/online/talkandtravel/service/impl/TokenServiceImpl.java
src/main/java/online/talkandtravel/service/impl/UserServiceImpl.java
src/main/java/online/talkandtravel/util/constants/UserConstants.java
src/main/resources/application.properties
src/main/resources/db/migration/V15__remove_constraint_user_email.sql
src/test/resources/application.properties

ticket - https://lizavol9.atlassian.net/browse/KAN-236?atlOrigin=eyJpIjoiYzkzODhhYzA4N2Q1NGJiMDgxNDk1OGIxNGJmMzRiMzAiLCJwIjoiaiJ9

KAN-236 delete user feature

---

src/main/java/online/talkandtravel/service/impl/TokenServiceImpl.java
src/main/resources/application.properties

ticket - https://lizavol9.atlassian.net/browse/KAN-242?atlOrigin=eyJpIjoiMDk4OGJjNzIzMWUyNDZmOGJmNzNkYWUyZjcyYTg3NzYiLCJwIjoiaiJ9

KAN-242 fix token time expire 

---

src/main/java/online/talkandtravel/model/entity/User.java

ticket - https://lizavol9.atlassian.net/browse/KAN-243?atlOrigin=eyJpIjoiNjU5MjBmZjdmMDNhNDc5MzlkNmRiMjAyM2ExOTI2ZjMiLCJwIjoiaiJ9

KAN-243 fix username length constraint
